apiVersion: v1
kind: Service
metadata:
  name: aise-se-service
spec:
  clusterIP: None
  ports:
    - name: aise-se
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.serviceport }}
  selector:
    app: "{{ template "aise-se.fullname" . }}-ist"
