apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aise-gd-cronjob
  namespace: {{ .Release.Namespace }}
spec:
  # Forbid代表不允许并发执行；如果新 Job 的执行时间到了而老 Job 没有执行完，
  # CronJob 会忽略新 Job 的执行即新job不会启动。适用于只允许一个任务实例运行的场景
  concurrencyPolicy: Forbid
  # 强烈建议设置失败任务数，用于排查任务失败根因，以优化任务
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  # 强烈建议设置错过调度的计算时间
  startingDeadlineSeconds: 200
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      # 串行执行
      parallelism: 1
      # 成功一次责当前job判定为完成
      completions: 1
      ttlSecondsAfterFinished: 100
      template:
        spec:
          serviceAccountName: admin
          containers:
          - name: cronjob
            image: "{{ .Values.cronjobImage }}:{{ .Values.cronjobImageTag }}"
            command: ["/bin/sh","/root/monitor_se.sh"]
            #command: ["tail","-f","/dev/null"]
            volumeMounts:
              - name: script
                mountPath: /root/monitor_se.sh
                subPath: monitor_se.sh
          restartPolicy: OnFailure
          #restartPolicy: Never
          volumes:
          - name: script
            configMap:
              name: aise-gd-cronjob-configmap

