apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.odp.name }}-configmap
    namespace: {{ .Release.Namespace }}
    labels:
        app: "odp"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
data:
    aise.conf: |
        [CamelConfig]
        [.ServiceConfig]
        
        [..Local]
        [...@Service]
        Name: face_aise
        DefaultPort: 30001
        DefaultRetry: 1
        DefaultConnectType: SHORT
        DefaultConnectTimeOut: 1000
        DefaultReadTimeOut: 10000
        DefaultWriteTimeOut: 10000
        EnableConnectRetry: Off
        [....@Server]
        Hostname : {{ .Values.odp.gd.ip }}
        Port: {{ .Values.odp.gd.port }}
        [....SuperStrategy]
        Balance : Random
        Hybrid : Off
        [....Protocol]
        Name: http
        [....Converter]
        Name: json

    feature.conf: |
        [CamelConfig]
        [.ServiceConfig]
        [..Local]
        [...@Service]
        Name: featureV3
        DefaultPort: 30001
        DefaultRetry: 1
        DefaultConnectType: SHORT
        DefaultConnectTimeOut: 200
        DefaultReadTimeOut: 3000
        DefaultWriteTimeOut: 3000
        EnableConnectRetry: Off
        [....@Server]
        Hostname : {{ .Values.odp.feature.ip }}
        Port: {{ .Values.odp.feature.port }}
        [....SuperStrategy]
        Package: RANDOM_PACK
        [....Protocol]
        Name: http
        [....Converter]
        Name: json


    php.conf: |
        server {
            listen              {{ .Values.odp.targetPort }};
            server_name         archive-api.example.com;
            more_set_headers    'Server: Apache';
            #set $php_upstream 'unix:/home/vis/install/tmp/odp/var/php-cgi.sock';
            set $php_upstream 'unix:/home/vis/install/tmp/odp/var/hhvm.sock';
        
        #########域名适配模块配置###############
            dna off;
            dna_adapt_path "/home/vis/install/tmp/odp/webserver/conf/adaption";
            dna_url_adaption "device";
            dna_cookie_adaption "device";
        
        #########OMP支持#######################
            #设置产品线
            set $product face;
            #设置子系统
            set $subsys faceapi;
            if ($http_x_bd_product) {
                #从接入层获取产品线
                set $product $http_x_bd_product;
            }
            if ($http_x_bd_subsys) {
                #从接入层获取子系统
                set $subsys $http_x_bd_subsys;
            }
        
        #   统一配置全局的rewrite规则请打开如下配置项，并配置当前目录下的rewrite文件
        #   include             vhost/rewrite;
        
            underscores_in_headers on;
            logid_name x_bd_logid;
        
        #   防盗链: 这个去掉，否则superarchive-v2-web在用svc访问odp时会抛403错误
        #    if ($host !~ "^((.*\.)?(example\.(com|com\.cn|cn)|91\.com)|localhost|\d{1,3}(\.\d{1,3}){3})(:\d+)?$") {
        #        return 403;
        #    }
        
            location ~* /(\.svn|CVS|Entries){
                deny all;
            }
        
            location ~* /((.*)\.(.*)\/(.*)\.php){
                deny all;
            }
        
            location ~* /\.(sql|bak|inc|old)$ {
                deny all;
            }
        
            location ~ ^/(favicon.ico|static) {
                root            /home/vis/install/tmp/odp/webroot;
            }
        
            location ~ \.php$ {
                root            /home/vis/install/tmp/odp/webroot;
                fastcgi_pass    $php_upstream;
                fastcgi_index   index.php;
                include         fastcgi.conf;
            }
        
            location / {
                root /home/vis/install/tmp/odp/webroot;
                index index.php;
                fastcgi_pass    $php_upstream;
                include         fastcgi.conf;
                rewrite ^/([^/.]*)(/[^\?]*)?((\?.*)?)$ /$1/index.php$2$3 break;
            }
        }
