apiVersion: v1
kind: Service
metadata:
  name: odp-service
spec:
  type: NodePort
  ports:
  - name: odp
    port: {{.Values.odp.port}}
    protocol: TCP
    targetPort: {{.Values.odp.targetPort}}
    nodePort: {{.Values.odp.nodePort}}
  selector:
    app: "odp"
