apiVersion: v1
data:
  database_init.sql: |2

    -- create db 'superarchivev2'
    CREATE DATABASE IF NOT EXISTS superarchivev2
      default character set utf8
      default collate utf8_general_ci;

    flush privileges;
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-db-create
  namespace: {{ .Release.Namespace }}
