#FROM centos7-gcc82-glibc-2.18:v1.0
FROM registry.example.com/ist/centos:7

ADD jdk1.8.0_131.tar.gz /data/aicu-tob/software/
ADD coreutils-8.22-18.el7.x86_64.rpm /tmp/coreutils-8.22-18.el7.x86_64.rpm
ADD superarchive-sync /data/aicu-tob/software/new/superarchive-sync

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && yum clean all && yum -y localinstall /tmp/coreutils-8.22-18.el7.x86_64.rpm && rm -rf /tmp/*.rpm

ENV JAVA_HOME=/data/aicu-tob/software/jdk1.8.0_131
ENV PATH=${PATH}:${JAVA_HOME}/bin
ENV TZ=Asia/Shanghai

WORKDIR /data/aicu-tob/software/new/superarchive-sync

CMD /bin/sh ./do_start.sh 
