apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.web.name }}-configmap
    namespace: {{ .Release.Namespace }}
    labels:
        app: "{{ .Values.web.name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
data:
    application.yml: |
        logging:
          config: classpath:logback-spring.xml
          directory: ./logs
        

        server:
          port: {{ .Values.web.targetPort }}
        
        spring:
          main:
            lazy-initialization: true
  
        
          redis:
            port: {{ .Values.web.redis.port }}
            host: {{ .Values.web.redis.ip }}
            database: {{ .Values.web.redis.db }}
            password: {{ .Values.web.redis.pass }}
            jedis:
              pool:
                max-active: 8
                max-wait: -1
                min-idle: 0
                max-idle: 8
              timeout: 5000ms
            # cache
            cache:
              type: caffeine
        patronum:
          cache:
            caffeine:
              basic-spec: expireAfterWrite=1800s
              spec:
                cache1: maximumSize=500,expireAfterWrite=1s
        
        aise:
          odp:
            url: http://{{ .Values.web.odp.ip }}:{{ .Values.web.odp.port }}/face-api/
        #    url: http://gpu-node.example.internal:8400/face-api/
            maxRetryTimes: 2
            retrySleepTimeMills: 200
          batch:
            pool:
              core: 1
              max: 5
              queueSize: 5
        
        
        feature:
          identify:
            minScore: 0.0
        
        document:
          history:
            feature:
              del:
                enable: true
            table:
              del:
                enable: true
          track:
            identify:
              minScore: 60
              topNumber: 10
              dictDes: trackIdentify
        brpc:
          global:
            client:
              protocol-type: 1 # rpc
  

        doc:
          feature:
            collection:
              id:
                prefix: qa_1202
                real.prefix: qa_1230_01
